[alembic]
# Path to migration scripts
script_location = %(here)s/alembic

# Logging configuration
# file_config = %(here)s/logging.ini

# Default environment prefix for configuration values
sqlalchemy.url = %(DATABASE_URL)s
